### ISSUE TITLE
Why prefetch?

### ISSUE THREAD

**Issue by jahvi** [magesuite/magepack-magento#7]
Currently the module is using "prefetch" link tags to hint the browser how scripts should be loaded:
https://github.com/magesuite/magepack-magento/blob/1.x/view/frontend/templates/bundles-loader.phtml#L10-L14

However prefetch is used to hint the browser about resources that will [most likely be used on the next navigation](https://web.dev/link-prefetch/), considering the scripts are loaded on the page they're supposed to be used this doesn't make a lot of sense.

Shouldn't this be using "preload" instead? The scripts are definitely needed on the page they're loaded on so it would help to get the browser to load them as soon as possible.

**Comment by mykhailo-superiorseating** [comment]
Because of "prefetch", looks like Chrome will request js bundles twice.
![Screenshot from 2021-01-12 15-23-01](https://user-images.githubusercontent.com/57410436/104368542-37317280-54ea-11eb-9167-1b4fe4c92d2b.png)

And "transferred over network" column shows bigger value.

**Comment by jahvi** [comment]
We changed this internally and we've had no issues, I'll submit a PR.

**Comment by erfanimani** [comment]
I don't have the problem of requesting bundling twice, this is most likely a configuration issue on your side @mykhailo-superiorseating — I'm not sure how this could happen.

@jahvi There are some advantages to prefetching instead of preloading, but correct me if I'm wrong:

* Preload can still delay first contentful paint as the resource is requested with high priority. Prefetch is lower priority, letting the browser decide when to download it. 
* The prefetch still happens between pageloads, whereas other HTTP requests are cancelled if they haven't finished. So if a user visits the homepage but navigates to a PDP before the page is fully loaded, bundle-common.min.js and bundle-cms.min.js continue loading, making the next pageload quicker.

> Shouldn't this be using "preload" instead? The scripts are definitely needed on the page they're loaded on so it would help to get the browser to load them as soon as possible.

Not sure if I agree with "as soon as possible". I would still prefer fonts, CSS and critical images to be loaded earlier.

Again, as far as I understand, the prefetch is purely there to let the browser decide when to download it, with low priority. Even if you remove the prefetch, the page will continue to work, and the RequireJS tree will be loaded as per normal.

Even though generally preload should be used for assets for the current pageload, I'm still leaning toward prefetch being appropriate in this scenario too. Perhaps there was some wisdom there from @krzksz ?

Also check https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf

**Comment by erfanimani** [comment]
I ended up finding the reason in this commit https://github.com/magesuite/magepack-magento/commit/a428637c5a8cd56df8d10a8ead0b43352bef5f8d which confirms my thoughts.

**Comment by jahvi** [comment]
@erfanimani I guess this depends on what you're going for, `preload` will by design increase the resource priority so it will be requested by the browser before hero images for example so it will have some impact on LCP, FCP. However it will positively TTI, SI, TBT and potentially even CLS (if your scripts mess with layout a lot)

To quote the article you linked, they advice this:

> Preload resources you have high-confidence will be used in the current page. Prefetch resources likely to be used for future navigations across multiple navigation boundaries.

`prefetch` is usually used for resources in future navigations, eg: if you go to the homepage you would load the `common` and `cms` bundle and if you know a lot of users then navigate to PDP after that then you can `prefetch` the `product` bundle so it's ready and PDP pages load "faster".

If your goal is to increase FCP/LCP then you can also `preload` your hero images (with a higher priority than the bundles) to make sure they're loaded in the right order. I can't find the link now but I seem to remember reading that this will be added as a recommendation to Lighthouse at some point.

In the context of Magento we found better results by `preloading` bundles since they're pretty much necessary in some cases anyways (out of the box add to cart and proceed to checkout buttons won't work before JS is loaded, the whole checkout page, etc) so preloading them tend to yield better results overall. We also `preload` hero images when possible to offset some of the LCP/FCP downsides.

**Comment by erfanimani** [comment]
Thanks for the response @jahvi, that does make sense.

**Comment by krzksz** [comment]
Hey, your research and assumptions are correct. In summary, Magepack's goal was to decrease TTI and in fact it was better with preload instead of prefetch. The problem was that it had negative impact on FCP and LCP because stylesheets had to compete with bundles for bandwidth during the initial load of the page which was unacceptable.

The ideal solution would be to somehow tell the browser to download bundles **without executing them** as soon as possible **without interfering with critical styles and images**, but I did not manage to find a way to do that so we went with prefetch instead.

If you really want then you can always override Magepack's template that loads bundles using Magento's inheritance mechanism, but I would like this base to stay as it is.

**Comment by krisdante** [comment]
@mykhailo-superiorseating please check if you have cache enabled when inspector is open, and also you are not hard reloading the page.

**Comment by mykhailo-superiorseating** [comment]
@krisdante Hi. We already fixed that and aren't able to check. Regarding the cache, the first visit is most important because there are no cached resources. Even if the current solution works good for secondary reloads it really doesn't make much sense - everything is already cached at that moment.

**Comment by jahvi** [comment]
Fair enough, I'll close this for now then.

**Comment by krisdante** [comment]
@mykhailo-superiorseating the first "normal" visit is something else than hard reloading or disabling cache. 
Even if you visit for the first time, the first request will download the file, the second one will get this from the cache. 

I am not talking here for secondary visits at all.

If you hard reload the no-cache header is added by the browser to all the requests. If you visit for the first time - it is not.
